export type BlogDataTypes = {
    id: number,
    title: string,
    description: string,
    image: string,
    tags: string[],
    authorImage: string,
    authorName: string,
    date_published: string,
    content?: any,
    createdBy: string,
    photoURL: string,
    createdAt: string,
    coverImage: string,
}