export type BlogDataTypes = {
    id: number,
    title: string,
    slug: string,
    uid: string,
    userEmail: string,
    createdAt: string,
    content: any,
    tags: string[],
    authorImage: string,
    authorName: string,
    date_published: string,
    createdBy: string,
    photoURL: string,
    coverImage: string,
    color_code: string,
}